// swift-tools-version:6.0
import PackageDescription

// Generated by scripts/generate-package-swift.sh. Do not edit by hand;
// changes are overwritten by the next release.

let package = Package(
    name: "FSSwiftUISelectors",
    // Deliberately no `platforms:`. Declaring one here becomes a floor that every consuming package
    // must also declare, and real apps embed SwiftUI code in packages that declare a lower floor or
    // none at all, which SwiftPM would then refuse to resolve. The framework is built for iOS 13 and
    // everything it exposes is guarded by `@available`, so it links at any deployment target.
    products: [
        // FSSwiftUISelectorsDependencies is part of this product on purpose. The framework's
        // .swiftinterface contains `import FullStory`, so anything compiling against
        // FSSwiftUISelectors needs the FullStory module on its search path and needs it linked.
        // A package-level dependency alone does not do that, which would leave anyone depending on
        // this package by itself failing with "Unable to find module dependency: 'FullStory'".
        .library(
            name: "FSSwiftUISelectors",
            targets: ["FSSwiftUISelectors", "FSSwiftUISelectorsDependencies"]
        ),
    ],
    dependencies: [
        // FSSwiftUISelectors is built against a specific FullStory build and the two are released in
        // lockstep, so this is pinned rather than ranged: selectors 1.75.0 requires FullStory 1.75.0.
        .package(url: "https://github.com/fullstorydev/fullstory-swift-package-ios", exact: "1.75.0"),
    ],
    targets: [
        .binaryTarget(
            name: "FSSwiftUISelectors",
            url: "https://ios-releases.fullstory.com/fullstory-swiftui-selectors-1.75.0-xcframework.zip",
            checksum: "815ce021c3a5c25468c26f4182282be4db3bd291a8e91a24bff8afc9b7209288"
        ),
        // Carries the FullStory dependency for the binary target above, which cannot declare
        // dependencies of its own. Contains no code.
        .target(
            name: "FSSwiftUISelectorsDependencies",
            dependencies: [
                .product(name: "FullStory", package: "fullstory-swift-package-ios"),
            ]
        ),
    ]
)
