// This target intentionally contains no code.
//
// FSSwiftUISelectors ships as a binary target, and SwiftPM does not allow a binary target to
// declare dependencies. The framework's .swiftinterface contains `import FullStory`, so consumers
// need the FullStory module on their search path and linked into their build. This target exists
// only to carry that dependency and is shipped as part of the FSSwiftUISelectors library product,
// so depending on FSSwiftUISelectors brings FullStory along automatically.
//
// See Package.swift, which is generated by scripts/generate-package-swift.sh.
