#!/usr/bin/env bash
#
# Writes the Package.swift for a fullstory-swiftui-selectors release.
#
# Usage: scripts/generate-package-swift.sh <version> <checksum> [output-path]
#
# There is no Package.swift bundled with the fullstory-swiftui-selectors
# xcframework (unlike the FullStory SDK, which publishes one alongside its
# release), so the manifest is generated here instead of downloaded.

set -euo pipefail

if [[ $# -lt 2 || $# -gt 3 ]]; then
    echo "Usage: $0 <version> <checksum> [output-path]" >&2
    exit 1
fi

version="$1"
checksum="$2"
output="${3:-Package.swift}"

if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "Error: version '$version' is not a valid semantic version." >&2
    exit 1
fi

if [[ ! "$checksum" =~ ^[0-9a-f]{64}$ ]]; then
    echo "Error: checksum '$checksum' is not a 64-character hex SHA-256." >&2
    exit 1
fi

cat > "$output" <<EOF
// swift-tools-version:6.0
import PackageDescription

// Generated by scripts/generate-package-swift.sh. Do not edit by hand;
// changes are overwritten by the next release.

let package = Package(
    name: "FSSwiftUISelectors",
    // Deliberately no \`platforms:\`. Declaring one here becomes a floor that every consuming package
    // must also declare, and real apps embed SwiftUI code in packages that declare a lower floor or
    // none at all, which SwiftPM would then refuse to resolve. The framework is built for iOS 13 and
    // everything it exposes is guarded by \`@available\`, so it links at any deployment target.
    products: [
        // FSSwiftUISelectorsDependencies is part of this product on purpose. The framework's
        // .swiftinterface contains \`import FullStory\`, so anything compiling against
        // FSSwiftUISelectors needs the FullStory module on its search path and needs it linked.
        // A package-level dependency alone does not do that, which would leave anyone depending on
        // this package by itself failing with "Unable to find module dependency: 'FullStory'".
        .library(
            name: "FSSwiftUISelectors",
            targets: ["FSSwiftUISelectors", "FSSwiftUISelectorsDependencies"]
        ),
    ],
    dependencies: [
        // FSSwiftUISelectors is built against a specific FullStory build and the two are released in
        // lockstep, so this is pinned rather than ranged: selectors ${version} requires FullStory ${version}.
        .package(url: "https://github.com/fullstorydev/fullstory-swift-package-ios", exact: "${version}"),
    ],
    targets: [
        .binaryTarget(
            name: "FSSwiftUISelectors",
            url: "https://ios-releases.fullstory.com/fullstory-swiftui-selectors-${version}-xcframework.zip",
            checksum: "${checksum}"
        ),
        // Carries the FullStory dependency for the binary target above, which cannot declare
        // dependencies of its own. Contains no code.
        .target(
            name: "FSSwiftUISelectorsDependencies",
            dependencies: [
                .product(name: "FullStory", package: "fullstory-swift-package-ios"),
            ]
        ),
    ]
)
EOF

echo "Wrote ${output} for version ${version}"
